### ISSUE TITLE
Fix zustand warning in frontend/lib/store/local-limit.ts

### ISSUE THREAD

**Issue by ahaapple** [memfreeme/memfree#87]
```
  console.warn
    [DEPRECATED] `getStorage`, `serialize` and `deserialize` options are deprecated. Use `storage` option instead.

      12 |
      13 | const useSearchLimit = create<SearchLimit>()(
    > 14 |     persist(
         |            ^
      15 |         (set, get) => ({
      16 |             searchCount: 0,
      17 |             lastSearchDate: new Date().toDateString(),

      at persistImpl (node_modules/zustand/middleware.js:599:15)
      at Object.<anonymous> (lib/store/local-limit.ts:14:12)
      at Object.<anonymous> (lib/store/tests/local-limit.test.ts:2:1)
```

I think we update the  local-limit.ts like frontend/lib/store/local-history.ts

**Comment by Riyan-Mo** [comment]
I could work on this.

**Comment by Riyan-Mo** [comment]
@ahaapple Close this as done.
